version: "3"

services:
  vote:
    image: ritikbilala/dockervotingapp_vote:latest
    volumes:
     - ./vote:/app
    ports: EXPOSE 80

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ritikbilala/dockervotingapp_worker:latest

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  result:
    build: ritikbilala/dockervotingapp_result:latest
    volumes:
      - ./result:/app
    ports: EXPOSE 8080
